import { Red_Hat_Display } from "next/font/google";
import "./globals.scss";

// Import Red Hat Display as a Google Font
const redHatDisplay = Red_Hat_Display({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Add any weights you need
  variable: "--font-red-hat-display",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={redHatDisplay.variable}>
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/remixicon@4.2.0/fonts/remixicon.css"
          rel="stylesheet"

        />

      </head>
      <body className="antialiased">{children}
       
      </body>
    </html>
  );
}
